<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCxmSRWZ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCxmSRWZ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCxmSRWZ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCxmSRWZ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCxmSRWZ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'CxmSRWZ',
    'container.build_id' => '11a45a92',
    'container.build_time' => 1537838870,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCxmSRWZ');
